config/routes.rb
Rails.application.routes.draw do

  get 'add_developers/new'

  get 'add_developers/create'

  get 'sessions/new'

  # root 'static_pages#home'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  # get 'signin', to: 'sessions#new'
  root "users#current_user_"

  post 'signin', to: 'sessions#create'

  delete 'signout', to: 'sessions#destroy'

  resources :users, only: [:update,:edit,:show,:index,:destroy]

  resources :account_activations, only: [:edit]

  resources :projects, only: [:index,:destroy]
  
  get '/new', to: 'users#new'

  get '/projects/:id/edit', to: 'projects#edit'

  patch '/projects/:id', to: 'projects#update'

  get '/users/:id/projects/new', to: 'projects#new'

  post '/users/:id/projects', to: 'projects#create'
  
  get '/projects/:iid/new_issue', to: 'projects#new_issue'

  get '/projects/:iid/show_issue', to: 'projects#show_issue'

  post '/projects/:iid/create_issue', to: 'projects#create_issue'

  get '/projects/:iid/show_issue_create/:id', to: 'projects#show_issue_create'

  get '/projects/:iid/edit_issue/:id', to: 'projects#edit_issue'

  patch '/projects/:iid/update_issue/:id', to: 'projects#update_issue'

  delete '/projects/:iid/delete_issue/:id', to: 'projects#destroy_issue'

  get '/projects/:iid', to: 'projects#show'

  default_url_options :host => "localhost:3000"

  get '/projects/:id/add_developers/new', to: 'add_developers#new'

  post '/projects/:id/add_developers', to: 'add_developers#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :issues
	has_many :relations, dependent: :destroy
	has_many :users, :through => :relations
	validates :project_name, presence: true, length: { maximum: 30 }
	validates :description, presence: true, length: { maximum: 140}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper
	skip_before_filter :verify_authenticity_token
	before_action :correct_user, only: [:edit, :update, :destroy]
	# before_action :correct_user_issue, only: [:edit_issue, :update_issue, :destroy_issue]
	def new
		@project = Project.new
		@user = User.find(params[:id])
	end
	def create
		@project = Project.new(params_project)
		user = User.find(@project.user_id)
		if @project.valid?
			flash.now[:success] = "Create project success"
			@project.save
			@relation = Relation.create(assign_id: @project.user_id, project_id: @project.id)
			redirect_to @project
		else
			render 'new'
		end
	end

	def show
		@project = Project.find_by(id: params[:iid])
			if !@project
				flash[:danger] = "Nothing"
				redirect_to root_url
			else
			end
	end

	def edit
		@project = Project.find_by(id: params[:id])
	end

	def update
		@project = Project.find_by(id: params[:id])
		if @project.update_attributes(params_project_edit)
			flash.now[:success] = "Your project is successfull updated"
			render 'show'
		else
			flash.now[:danger] = "Project update fail"
			render 'edit'
		end
	end
	
	def destroy
		project = Project.find(params[:id])
		project.destroy
		flash[:success] = "Project deleted"
		redirect_to current_user
	end

	def new_issue
		@issue = Issue.new
		@project = Project.find(params[:iid])
		@status = ['New', 'Inprogress', 'Resolved', 'Closed']
		@priority = ['Low','Normal','Hight','Urgent','Immediate']
		@rela = Relation.where(project_id: @project.id)
		@assign = []
		@rela.each.with_index do |rela,i|
      @assign[i] = User.find_by(id: rela.assign_id)
    end
	end

	def create_issue
		@project = Project.find(params[:iid])
		@issue = Issue.new(params_issue)
		if @issue.save
			Log.create(issue_id: @issue.id,creator_id: current_user.id,log_status: @issue.status,log_priority: @issue.priority)
			flash[:success] = "Create issue success"
			redirect_to "/projects/#{@project.id}/show_issue"
		else
			redirect_to "/projects/#{@project.id}/new_issue"
		end
	end

	def show_issue_create
		@issue = Issue.find(params[:id])
		@user = User.find(@issue.user_id)
		@project = Project.find(params[:iid])
    @log = Log.where(issue_id: @issue.id)
    @update = []
    @status = []
    @priority = []
    for i in 0...@log.count
      issue = Issue.find(@log[i].issue_id)
      creator = User.find_by(id: @log[i].creator_id)
      update_by = User.find_by(id: @log[i].update_by)
      tim = distance_of_time_in_words(@log[i].updated_at.time, Time.now)
      if i == 0
        @create = "<strong>Created</strong> by #{creator.account} #{tim} ago"
      else
        if @log[i-1].log_status != @log[i].log_status && @log[i-1].log_priority != @log[i].log_priority
          @update[i] = "<strong>Updated</strong> by #{update_by.account} #{tim} ago"
          @status[i] = "<strong>Status</strong> changed from <strong>#{@log[i-1].log_status}</strong> to <strong>#{@log[i].log_status}</strong>"
          @priority[i] = "<strong>Priority</strong> changed from <strong>#{@log[i-1].log_priority}</strong> to <strong>#{@log[i].log_priority}</strong>"

        elsif @log[i-1].log_status != @log[i].log_status
          @update[i] = "<strong>Updated</strong> by #{update_by.account} #{tim} ago"
          @status[i] = "<strong>Status</strong> changed from <strong>#{@log[i-1].log_status}</strong> to <strong>#{@log[i].log_status}</strong>"

        elsif @log[i-1].log_priority != @log[i].log_priority
          @update[i] = "<strong>Updated</strong> by #{update_by.account} #{tim} ago"
          @priority[i] = "<strong>Priority</strong> changed from <strong>#{@log[i-1].log_priority}</strong> to <strong>#{@log[i].log_priority}</strong>"

        else
        end
      end
    end
	end

	def show_issue
		@project = Project.find(params[:iid])
	end

	def edit_issue
		@project = Project.find(params[:iid])
		@issue = Issue.find(params[:id])
		@user = User.find(@issue.user_id)
		@current_assign = User.find_by(id: @issue.assign_id)
		@status = ['New', 'Inprogress', 'Resolved', 'Closed']
		@priority = ['Low','Normal','Hight','Urgent','Immediate']
		@rela = Relation.where(project_id: @project.id)
		@assign = []
		@rela.each.with_index do |rela,i|
      @assign[i] = User.find_by(id: rela.assign_id)
    end
	end

	def update_issue
		@project = Project.find(params[:iid])
		@issue = Issue.find(params[:id])
		if @issue.update_attributes(params_issue)
			Log.create(issue_id: @issue.id,update_by: current_user.id,log_status: @issue.status,log_priority: @issue.priority)
			flash.now[:success] = "Your issue is successfull updated"
			redirect_to "/projects/#{@project.id}/show_issue_create/#{@issue.id}"
		else
			flash.now[:danger] = "Issue update fail"
			render 'edit_issue'
		end
	end

	def destroy_issue
		issue = Issue.find(params[:id])
		issue.destroy
		flash.now[:success] = "Issue deleted"
		project = Project.find(issue.project_id)
		user = User.find(current_user.id)
		redirect_to "/projects/#{issue.project_id}/show_issue"
	end

	def correct_user
		project = Project.find(params[:id])
		user = User.find(project.user_id)
    return true if current_user == user
    flash[:danger] = "You cant edit another user"
    redirect_to root_url
  end

  def correct_user_issue
  	issue = Issue.find(params[:id])
  	return true if current_user.id == issue.user_id
  	flash[:danger] = "You are not issue of manager"
  	redirect_to "/projects/#{issue.project_id}/show_issue"
  end

	private
		def params_project
			params.require(:project).permit(:project_name,:description,:user_id)
		end
		def params_project_edit
			params.require(:project).permit(:project_name,:description)
		end
		def params_issue
			params.require(:issue).permit(:issue_name,:issue_decription,:assign_id,:project_id,:user_id,:status,:priority,:start_date,:due_date)
		end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/add_developer.html.erb
<% provide(:title, "Add developer") %>
<% if @project.assign_id == nil %>
	<div class="row">
		<div class="col-md-6">
			<p>Project name: <%= @project.project_name %></p>
			<p>Description:</p> <%= simple_format(@project.description) %>
		</div>
		<div class="col-md-6">
			<strong>Manager:</strong> <%= @project.user.account %><br/>
			<strong>Developer:</strong> Nobody
		</div>
	</div>
<% else %>
	<% @user = User.find(@project.assign_id) %>
	<div class="row">
		<div class="col-md-6">
			<p>Project name: <%= @project.project_name %></p>
			<p>Description:</p> <%= simple_format(@project.description) %>
		</div>
		<div class="col-md-6">
			<strong>Manager:</strong> <%= @project.user.account %><br/>
			<strong>Developer:</strong> <%= @user.account %>
		</div>
	</div>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title,"Edit project") %>
<h1>Edit project</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@project, url: "/projects/#{@project.id}", method: :patch) do |f| %>

      <%= render 'shared/errors_project' %>
			<%= f.label :project_name, "Project name" %>
      <%= f.text_field :project_name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: "4" %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/edit_issue.html.erb
<% provide(:title,"Edit issue") %>
<h1>Edit issue</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@issue, url: {action: :update_issue, controller: :projects}) do |f| %>

      <%= render 'shared/errors_issue' %>
			<%= f.label :issue_name %>
      <%= f.text_field :issue_name, class: 'form-control' %>

      <%= f.label :issue_decription, "Description" %>
      <%= f.text_area :issue_decription, class: 'form-control', rows: "6" %>

    
      <br/>
      <div class="row">
        <div class="col-md-4 col1">
          <%= f.label :assign_id %>
          <%= f.select :assign_id, options_for_select(@assign.map{ |us| [us.account, us.id] }, @current_assign.id), class: 'form-control' %>
        </div>

        <div class="col-md-4 col2">
          <%= f.label :status %>
          <%= f.select :status, options_for_select(@status.map{ |st| [st] }, @issue.status)%>
        </div>

        <div class="col-md-4 col3">
          <%= f.label :priority %>
          <%= f.select :priority, options_for_select(@priority.map{ |pr| [pr] }, @issue.priority) %>
        </div>     
      </div>
      <br/>
      <%= f.label :start_date %>
      <%= f.date_select :start_date, class: 'form-control', :start_year => Time.now.year, :end_year => Time.now.year + 10 %>

      <%= f.hidden_field :project_id, :value => @project.id,class: 'form-control' %>

      <%= f.hidden_field :user_id, :value => @user.id,class: 'form-control' %>

      <%= f.label :due_date, class: 'str' %>
      <%= f.date_select :due_date, class: 'form-control', :start_year => Time.now.year, :end_year => Time.now.year + 10 %>
      <br/>
      <br/>

      <%= f.submit "Update issue", class: "btn btn-info" %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title,"Create project") %>
<h1>Create project</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <% if @user.nil? %>
      <%= render 'shared/errors_project' %>
    <% else %>
      <%= form_for(@project, url: "/users/#{@user.id}/projects", method: :post) do |f| %>

        <%= render 'shared/errors_project' %>
  			<%= f.label :project_name, "Project name" %>
        <%= f.text_field :project_name, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: "4" %>
        
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.submit "Create project", class: "btn btn-info" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new_developer.html.erb
<% provide(:title,"Add developer") %>
<h1>Add developer</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 rieng3">
    <%= form_for(@project, url: "add_developer", method: :patch) do |f| %>
      <% users = User.all %>
      <%= f.label :assign_id %>
      <%= f.select :assign_id, options_for_select(users.map{ |us| [us.account, us.id] }), class: 'form-control' %>
      
      <%= f.hidden_field :project_id, :value => @project.id,class: 'form-control' %>
      
      <%= f.submit "Add developer", class: "btn btn-info rieng2" %>
    <% end %>
  </div>
</div>

app/views/projects/new_issue.html.erb
<% provide(:title,"Create issue") %>
<h1>Create issue</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@issue, url: "create_issue", method: :post) do |f| %>

      <%= render 'shared/errors_issue' %>
			<%= f.label :issue_name %>
      <%= f.text_field :issue_name, class: 'form-control' %>

      <%= f.label :issue_decription, "Description" %>
      <%= f.text_area :issue_decription, class: 'form-control', rows: "6" %>

    
      <br/>
      <div class="row">
        <div class="col-md-4 col1">
          <%= f.label :assign_id %>
          <%= f.select :assign_id, options_for_select(@assign.map{ |us| [us.account, us.id] }), class: 'form-control' %>
        </div>

        <div class="col-md-4 col2">
          <%= f.label :status %>
          <%= f.select :status, options_for_select(@status.map{ |st| [st] })%>
        </div>

        <div class="col-md-4 col3">
          <%= f.label :priority %>
          <%= f.select :priority, options_for_select(@priority.map{ |pr| [pr] }, @priority[1]) %>
        </div>     
      </div>

      <br/>
      
      <%= f.label :start_date %>
      <%= f.date_select :start_date, class: 'form-control', :start_year => Time.now.year, :end_year => Time.now.year + 10 %>

      <%= f.hidden_field :project_id, :value => @project.id, class: 'form-control' %>

      <%= f.hidden_field :user_id, :value => current_user.id, class: 'form-control' %>

      <%= f.label :due_date, class: 'str' %>
      <%= f.date_select :due_date, class: 'form-control', :start_year => Time.now.year, :end_year => Time.now.year + 10 %>
      <br/>
      <br/>

      <%= f.submit "Create issue", class: "btn btn-info" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% boss_project = User.find(@project.user_id) %>
<% provide(:title, "#{current_user.account} - Project #{@project.id}") %>

<p>People created: <%= boss_project.account %></p>
<p>Project name: <%= @project.project_name %></p>
<p>Description:</p> <%= simple_format(@project.description) %>
<% if current_user.id ==  @project.user_id %>
	<%= link_to "Edit project", "/projects/#{@project.id}/edit", class: 'btn btn-info' %>
	<%= link_to "Delete project", project_path(@project.id), method: :delete, data: { confirm: "Are you sure?" },class: 'btn btn-info' %>
	<%= link_to "Add developer", "/projects/#{@project.id}/add_developers/new", class: 'btn btn-info' %>
<% end %>

app/views/projects/show_issue.html.erb
<% provide(:title, "All issue") %>
<% if @project.issues.nil? %>

<% else %>
	<table class="table table-striped">
		<thead>
			<th>Subject</th>
			<th>Status</th>
			<th>Priority</th>
			<th>Creator</th>
			<th>Assign</th>
		</thead>
		<% @project.issues.each do |pr| %>
			<% assign = User.find(pr.assign_id) %>
			<% user = User.find(current_user.id) %>
			<% users = User.find(pr.user_id) %>
			<tbody>
				<tr>
					<td><%= link_to pr.issue_name, "show_issue_create/#{pr.id}" %></td>
					<td><%= pr.status %></td>
					<td><%= pr.priority %></td>
					<td><%= users.account %></td>
					<td><%= assign.account %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/projects/show_issue_create.html.erb
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
	table, tr, td{
		border: 1px solid #EEE;
		padding-left: 10px;
	}
	.row1 > .td1{
		width: 150px;
		height: 40px;
	}
	.row1 > .td2{
		width: 250px;
	}
	.row2, .row3, .row4{
		height: 40px;
	}
	p{
		margin-top: 10px;
	}
</style>
</head>
<body>
	<% provide(:title, "Issue - #{@issue.id}") %>
	<p>Subject: <%= @issue.issue_name %><br/></p>
  <% log = Log.where(issue_id: @issue.id) %>
  <% assign = User.find(@issue.assign_id) %>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<table style="box-shadow: 0 0 10px rgba(0,0,0,0.5);margin: 30px 0;">
					<tr class="row1">
						<td class="td1"><strong>Status:</strong></td>
						<td class="td2"><%= @issue.status %></td>
						<td class="td1"><strong>Start date:</strong></td>
						<td class="td2"><%= @issue.start_date %></td>
					</tr>
					<tr class="row2">
						<td><strong>Priority:</strong></td>
						<td><%= @issue.priority %></td>
						<td><strong>Due date:</strong></td>
						<td><%= @issue.due_date %></td>
					</tr>
					<tr class="row3">
						<td><strong>Manager:</strong></td>
						<td><%= @user.account %></td>
						<td><strong>Developer:</strong></td>
						<td><%= assign.account %></td>
					</tr>
					<tr class="row4">
						<td><strong>Category:</strong></td>
						<td>-</td>
						<td><strong>Done:</strong></td>
						<td style="padding: 0">
							<table>
								<tr>
									<td style="background-color: #EEE; width: 125px; height: 40px;"></td>
									<td style="width: 125px;">0%</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>

				<%= link_to "Edit issue", "/projects/#{@project.id}/edit_issue/#{@issue.id}", class: 'btn btn-info' %>
				<%= link_to "Delete issue", "/projects/#{@project.id}/delete_issue/#{@issue.id}", method: :delete, data: { confirm: "Are you sure" }, class: 'btn btn-info' %>
			</div>
		</div>
	</div>
	<p>History:</p>	

		<%= @create.html_safe %>
		<hr>
    <% for i in 0...@log.count %>
      <% if @update[i] %>
        <%= @update[i].html_safe %><br>
        <% if @status[i] %>
          <%= @status[i].html_safe %><br>
        <% end %>
        <% if @priority[i] %>
          <%= @priority[i].html_safe %><br>
        <% end %>
        <hr>
      <% else %>
      <% end %>
    <% end %>
</body>
</html>