config/routes.rb
Rails.application.routes.draw do

  get 'add_developers/new'

  get 'add_developers/create'

  get 'sessions/new'

  # root 'static_pages#home'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  # get 'signin', to: 'sessions#new'
  root "users#current_user_"

  post 'signin', to: 'sessions#create'

  delete 'signout', to: 'sessions#destroy'

  resources :users, only: [:update,:edit,:show,:index,:destroy]

  resources :account_activations, only: [:edit]

  resources :projects, only: [:index,:destroy]
  
  get '/new', to: 'users#new'

  get '/projects/:id/edit', to: 'projects#edit'

  patch '/projects/:id', to: 'projects#update'

  get '/users/:id/projects/new', to: 'projects#new'

  post '/users/:id/projects', to: 'projects#create'
  
  get '/projects/:iid/new_issue', to: 'projects#new_issue'

  get '/projects/:iid/show_issue', to: 'projects#show_issue'

  post '/projects/:iid/create_issue', to: 'projects#create_issue'

  get '/projects/:iid/show_issue_create/:id', to: 'projects#show_issue_create'

  get '/projects/:iid/edit_issue/:id', to: 'projects#edit_issue'

  patch '/projects/:iid/update_issue/:id', to: 'projects#update_issue'

  delete '/projects/:iid/delete_issue/:id', to: 'projects#destroy_issue'

  get '/projects/:iid', to: 'projects#show'

  default_url_options :host => "localhost:3000"

  get '/projects/:id/add_developers/new', to: 'add_developers#new'

  post '/projects/:id/add_developers', to: 'add_developers#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to image_tag("logo.png", :height => 17), current_user %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in || @project %>
          <li><%= link_to "Users", current_user %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li> <!---->
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
      		<ul class="nav navbar-nav navbar-right">
      			<li><%= link_to "Sign in", root_path %></li>
            <li><%= link_to "Sign up", "/new" %></li>
          </ul>
        <% end %>
      </ul>
    </nav>
	</div>
</nav>

<% if !@project.nil? %>
  <nav class="navbar navbar-default", id="navb">
    <div class="container">
        <div class="row">
          <div class="col-md-4">
            <nav>
              <ul class="nav navbar-nav">
                <li><%= link_to "Overview", "/projects/#{@project.id}/show_issue" %></li>
              </ul> 
            </nav>
          </div>
          <div class="col-md-4">
            <nav>
              <ul class="nav navbar-nav">
                <li><%= link_to "Issue", "/projects/#{@project.id}/show_issue" %></li>
              </ul>
            </nav>
          </div>
          <div class="col-md-4">
            <nav>
              <ul class="nav navbar-nav">
                <li><%= link_to "New issue", "/projects/#{@project.id}/new_issue" %></li>
              </ul>
            </nav>
          </div>
        </div>
    </div>
  </nav>
<% end %>

<% if logged_in %>
  <nav class="navbar navbar-inverse naq">
    <div class="nav navbar navbar-right">
      <button class="btn btn-danger btnr">Select project</button>
      <div id="prj">
        <ul style="margin-top: 7px;">
          <% rela = Relation.where(assign_id: current_user.id) %>
          <% rela.each do |pr| %>
            <% project = Project.find(pr.project_id) %>
            <li><%= link_to project.project_name, "/projects/#{project.id}", class: 'dsprj' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
  		<% flash.each do |key,value| %>
				<div class="alert alert-<%=key%>"><%= value %></div>
  		<% end %>
    	<%= yield %>
    </div>
  </body>
</html>